import type {
  User,
  Vehicle,
  Client,
  Appointment,
  Sale,
  DashboardStats,
  Expense,
  ForumPost,
  VehicleServiceRecord,
  ClientVehicleInfo,
} from "@/types";

// ─── Usuarios (uno por rol) ───────────────────────────────────────────────────

export const users: User[] = [
  {
    id: "u1",
    name: "Carlos Martínez",
    email: "carlos.martinez@dealerhub.es",
    role: "admin",
    phone: "612 345 678",
    createdAt: "2024-01-10",
  },
  {
    id: "u2",
    name: "Laura Sánchez",
    email: "laura.sanchez@dealerhub.es",
    role: "vendedor",
    phone: "623 456 789",
    createdAt: "2024-02-15",
  },
  {
    id: "u3",
    name: "Alejandro Pérez",
    email: "alejandro.perez@dealerhub.es",
    role: "mecanico",
    phone: "634 567 890",
    createdAt: "2024-03-01",
  },
  {
    id: "u4",
    name: "María González",
    email: "maria.gonzalez@dealerhub.es",
    role: "recepcionista",
    phone: "645 678 901",
    createdAt: "2024-03-20",
  },
  {
    id: "u5",
    name: "Visor Externo",
    email: "viewer@dealerhub.es",
    role: "viewer",
    createdAt: "2024-04-01",
  },
];

// ─── Vehículos (15, marcas europeas) ─────────────────────────────────────────

export const vehicles: Vehicle[] = [
  {
    id: "v1",
    brand: "BMW",
    model: "Serie 3 320d",
    year: 2022,
    color: "Blanco Alpino",
    licensePlate: "1234 ABC",
    vin: "WBA5A110X0D123456",
    mileage: 28000,
    purchasePrice: 26000,
    price: 32900,
    fuelType: "diesel",
    transmission: "automático",
    status: "disponible",
    description: "Vehículo en excelente estado, un propietario anterior.",
    images: [],
    createdAt: "2025-09-01",
  },
  {
    id: "v2",
    brand: "Mercedes-Benz",
    model: "Clase C 220d",
    year: 2021,
    color: "Negro Obsidiana",
    licensePlate: "5678 DEF",
    vin: "WDD2050151R234567",
    mileage: 45000,
    purchasePrice: 23000,
    price: 29500,
    fuelType: "diesel",
    transmission: "automático",
    status: "disponible",
    description: "Mantenimiento oficial al día. Equipamiento AMG Line.",
    images: [],
    createdAt: "2025-09-05",
  },
  {
    id: "v3",
    brand: "Volkswagen",
    model: "Golf 8 GTI",
    year: 2023,
    color: "Gris Nardo",
    licensePlate: "9012 GHI",
    vin: "WVWZZZ1KZAW345678",
    mileage: 12000,
    purchasePrice: 31000,
    price: 38500,
    fuelType: "gasolina",
    transmission: "manual",
    status: "reservado",
    description: "Casi nuevo. Paquete Performance incluido.",
    images: [],
    createdAt: "2025-10-10",
  },
  {
    id: "v4",
    brand: "Audi",
    model: "A4 Avant 35 TDI",
    year: 2021,
    color: "Azul Navarra",
    licensePlate: "3456 JKL",
    vin: "WAUZZZ8K1BA456789",
    mileage: 62000,
    purchasePrice: 19000,
    price: 24800,
    fuelType: "diesel",
    transmission: "automático",
    status: "disponible",
    description: "Familiar muy espacioso. Revisiones en concesionario oficial.",
    images: [],
    createdAt: "2025-10-15",
  },
  {
    id: "v5",
    brand: "SEAT",
    model: "León FR 2.0 TSI",
    year: 2023,
    color: "Rojo Desire",
    licensePlate: "7890 MNO",
    vin: "VSSZZZ5FZM567890",
    mileage: 8500,
    purchasePrice: 22000,
    price: 27900,
    fuelType: "gasolina",
    transmission: "manual",
    status: "disponible",
    description: "Primera matrícula en 2023. Garantía fabricante vigente.",
    images: [],
    createdAt: "2025-11-01",
  },
  {
    id: "v6",
    brand: "Peugeot",
    model: "308 SW 1.5 BlueHDi",
    year: 2022,
    color: "Verde Olivino",
    licensePlate: "2345 PQR",
    vin: "VF3LCYHZPLS678901",
    mileage: 33000,
    purchasePrice: 17500,
    price: 22400,
    fuelType: "diesel",
    transmission: "automático",
    status: "disponible",
    description: "Familiar con maletero amplio. Conexión CarPlay.",
    images: [],
    createdAt: "2025-11-10",
  },
  {
    id: "v7",
    brand: "Renault",
    model: "Mégane E-Tech 100% Eléctrico",
    year: 2023,
    color: "Azul Hierro",
    licensePlate: "6789 STU",
    vin: "VF1BM000X68789012",
    mileage: 5200,
    purchasePrice: 28000,
    price: 34600,
    fuelType: "eléctrico",
    transmission: "automático",
    status: "disponible",
    description: "Autonomía 470 km WLTP. Cargador rápido 130 kW incluido.",
    images: [],
    createdAt: "2025-11-20",
  },
  {
    id: "v8",
    brand: "Volvo",
    model: "XC40 Recharge",
    year: 2022,
    color: "Blanco Crystal",
    licensePlate: "1122 VWX",
    vin: "YV1XZ56K1L1890123",
    mileage: 21000,
    purchasePrice: 33000,
    price: 41200,
    fuelType: "eléctrico",
    transmission: "automático",
    status: "en_taller",
    description: "SUV eléctrico premium. Pantalla Google integrada.",
    images: [],
    createdAt: "2025-12-01",
  },
  {
    id: "v9",
    brand: "Opel",
    model: "Insignia Grand Sport 2.0 CDTi",
    year: 2020,
    color: "Plata Sovereign",
    licensePlate: "3344 YZA",
    vin: "W0L000000K0901234",
    mileage: 78000,
    purchasePrice: 14500,
    price: 18900,
    fuelType: "diesel",
    transmission: "automático",
    status: "disponible",
    description: "Berlina ejecutiva. Navegación y sensores de aparcamiento.",
    images: [],
    createdAt: "2025-12-10",
  },
  {
    id: "v10",
    brand: "Škoda",
    model: "Octavia Combi 2.0 TDI",
    year: 2021,
    color: "Gris Magnetic",
    licensePlate: "5566 BCD",
    vin: "TMBZZZ5EZM5012345",
    mileage: 55000,
    purchasePrice: 16500,
    price: 21500,
    fuelType: "diesel",
    transmission: "manual",
    status: "disponible",
    description: "Coche de empresa con historial completo.",
    images: [],
    createdAt: "2025-12-15",
  },
  {
    id: "v11",
    brand: "Toyota",
    model: "Corolla 1.8 Hybrid",
    year: 2022,
    color: "Blanco Perla",
    licensePlate: "7788 EFG",
    vin: "SB1E76BE70E123456",
    mileage: 19500,
    purchasePrice: 21000,
    price: 26800,
    fuelType: "híbrido",
    transmission: "automático",
    status: "disponible",
    description: "Híbrido de bajo consumo. Ideal para ciudad.",
    images: [],
    createdAt: "2026-01-05",
  },
  {
    id: "v12",
    brand: "Ford",
    model: "Focus ST 2.3 EcoBoost",
    year: 2021,
    color: "Naranja Fury",
    licensePlate: "9900 HIJ",
    vin: "WF0DXXGCHDKA23456",
    mileage: 41000,
    purchasePrice: 18500,
    price: 23700,
    fuelType: "gasolina",
    transmission: "manual",
    status: "vendido",
    description: "280 CV de potencia. Llantas de 19\" de serie.",
    images: [],
    createdAt: "2026-01-10",
  },
  {
    id: "v13",
    brand: "Citroën",
    model: "C5 Aircross Hybrid 225",
    year: 2023,
    color: "Azul Perla",
    licensePlate: "1133 KLM",
    vin: "VF7SZKHNXMT234567",
    mileage: 14000,
    purchasePrice: 25000,
    price: 31400,
    fuelType: "híbrido",
    transmission: "automático",
    status: "disponible",
    description: "SUV enchufable con 55 km de autonomía eléctrica.",
    images: [],
    createdAt: "2026-01-20",
  },
  {
    id: "v14",
    brand: "Porsche",
    model: "Macan S",
    year: 2021,
    color: "Rojo Carmine",
    licensePlate: "2244 NOP",
    vin: "WP1ZZZ95ZLB345678",
    mileage: 36000,
    purchasePrice: 47000,
    price: 58900,
    fuelType: "gasolina",
    transmission: "automático",
    status: "reservado",
    description: "SUV deportivo. Paquete Sport Chrono incluido.",
    images: [],
    createdAt: "2026-02-01",
  },
  {
    id: "v15",
    brand: "Fiat",
    model: "500e 42 kWh",
    year: 2023,
    color: "Verde Menta",
    licensePlate: "3355 QRS",
    vin: "ZFABF3BCX00456789",
    mileage: 9800,
    purchasePrice: 18000,
    price: 22900,
    fuelType: "eléctrico",
    transmission: "automático",
    status: "disponible",
    description: "Urbano eléctrico con techo abatible. Autonomía 320 km.",
    images: [],
    createdAt: "2026-02-10",
  },
];

// ─── Clientes (10 españoles) ──────────────────────────────────────────────────

export const clients: Client[] = [
  {
    id: "c1",
    name: "Antonio Rodríguez García",
    email: "antonio.rodriguez@gmail.com",
    phone: "656 123 456",
    dni: "12345678A",
    address: "Calle Mayor 15, 3ºB",
    city: "Madrid",
    postalCode: "28001",
    createdAt: "2025-03-10",
  },
  {
    id: "c2",
    name: "Isabel Fernández López",
    email: "isabel.fernandez@hotmail.com",
    phone: "667 234 567",
    dni: "23456789B",
    address: "Av. Diagonal 452, 1ºA",
    city: "Barcelona",
    postalCode: "08037",
    notes: "Cliente habitual. Prefiere contacto por email.",
    createdAt: "2025-04-22",
  },
  {
    id: "c3",
    name: "Miguel Ángel Torres",
    email: "miguel.torres@yahoo.es",
    phone: "678 345 678",
    dni: "34567890C",
    address: "C/ Sierpes 8, 2ºC",
    city: "Sevilla",
    postalCode: "41004",
    createdAt: "2025-05-15",
  },
  {
    id: "c4",
    name: "Carmen Ruiz Moreno",
    email: "carmen.ruiz@outlook.com",
    phone: "689 456 789",
    dni: "45678901D",
    address: "Gran Vía 22, 4ºD",
    city: "Bilbao",
    postalCode: "48001",
    notes: "Interesada en vehículos eléctricos.",
    createdAt: "2025-06-08",
  },
  {
    id: "c5",
    name: "Javier Navarro Blanco",
    email: "javier.navarro@gmail.com",
    phone: "690 567 890",
    dni: "56789012E",
    address: "C/ Colón 5, 1ºB",
    city: "Valencia",
    postalCode: "46004",
    createdAt: "2025-07-19",
  },
  {
    id: "c6",
    name: "Lucía Morales Vega",
    email: "lucia.morales@empresa.es",
    phone: "601 678 901",
    dni: "67890123F",
    address: "Paseo de la Castellana 100, 8ºA",
    city: "Madrid",
    postalCode: "28046",
    notes: "Compra para flota de empresa.",
    createdAt: "2025-08-30",
  },
  {
    id: "c7",
    name: "Francisco Jiménez Ortega",
    email: "fran.jimenez@icloud.com",
    phone: "612 789 012",
    dni: "78901234G",
    address: "C/ Larios 3",
    city: "Málaga",
    postalCode: "29005",
    createdAt: "2025-10-05",
  },
  {
    id: "c8",
    name: "Elena Castro Prieto",
    email: "elena.castro@gmail.com",
    phone: "623 890 123",
    dni: "89012345H",
    address: "Rambla Nova 45, 3ºC",
    city: "Tarragona",
    postalCode: "43001",
    createdAt: "2025-11-14",
  },
  {
    id: "c9",
    name: "Pablo Serrano Díaz",
    email: "pablo.serrano@hotmail.es",
    phone: "634 901 234",
    dni: "90123456I",
    address: "C/ Paz 12, bajo A",
    city: "Zaragoza",
    postalCode: "50001",
    notes: "Busca coche familiar para segunda compra.",
    createdAt: "2025-12-02",
  },
  {
    id: "c10",
    name: "Rosa Alonso Herrera",
    email: "rosa.alonso@gmail.com",
    phone: "645 012 345",
    dni: "01234567J",
    address: "C/ Ancha 7, 2ºA",
    city: "A Coruña",
    postalCode: "15001",
    createdAt: "2026-01-17",
  },
];

// ─── Citas de taller (8) ──────────────────────────────────────────────────────

export const appointments: Appointment[] = [
  {
    id: "a1",
    clientId: "c8",
    vehicleId: "v8",
    mechanicId: "u3",
    date: "2026-03-16T09:00:00",
    serviceType: "diagnostico",
    status: "pendiente",
    description: "El vehículo muestra error en pantalla relacionado con la batería de alto voltaje.",
    estimatedCost: 120,
  },
  {
    id: "a2",
    clientId: "c1",
    vehicleId: "v1",
    mechanicId: "u3",
    date: "2026-03-17T10:30:00",
    serviceType: "cambio_aceite",
    status: "pendiente",
    description: "Cambio de aceite y filtros en revisión de 30.000 km.",
    estimatedCost: 180,
  },
  {
    id: "a3",
    clientId: "c3",
    vehicleId: "v9",
    mechanicId: "u3",
    date: "2026-03-18T12:00:00",
    serviceType: "frenos",
    status: "pendiente",
    description: "Revisión y cambio de pastillas de freno traseras.",
    estimatedCost: 320,
  },
  {
    id: "a4",
    clientId: "c5",
    vehicleId: "v10",
    mechanicId: "u3",
    date: "2026-03-12T09:00:00",
    serviceType: "revision_general",
    status: "completada",
    description: "Revisión general previa a la venta. Todo en orden.",
    estimatedCost: 250,
    finalCost: 250,
    notes: "Revisión superada. Vehículo apto para venta.",
    mileageAtService: 89500,
    closedAt: "2026-03-12T14:30:00",
    workItems: [
      { description: "Revisión de niveles (aceite, refrigerante, frenos)", cost: 0 },
      { description: "Comprobación de frenos y suspensión", cost: 80 },
      { description: "Diagnosis electrónica completa", cost: 60 },
      { description: "Cambio filtro de habitáculo", parts: "Filtro Mann CUK 2939", cost: 35 },
      { description: "Limpieza y ajuste general", cost: 75 },
    ],
    workPhotos: [],
    mechanicNotes: "Vehículo en buen estado general. Neumáticos al 60% de vida. Próximo cambio de aceite en 5.000 km.",
  },
  {
    id: "a5",
    clientId: "c2",
    vehicleId: "v2",
    mechanicId: "u3",
    date: "2026-03-10T11:00:00",
    serviceType: "aire_acondicionado",
    status: "completada",
    description: "Recarga de gas y revisión del sistema de climatización.",
    estimatedCost: 95,
    finalCost: 110,
    notes: "Se detectó pequeña fuga en junta. Reparada.",
    mileageAtService: 42300,
    closedAt: "2026-03-10T14:00:00",
    workItems: [
      { description: "Recarga gas R134a", parts: "Gas refrigerante R134a 500g", cost: 45 },
      { description: "Reparación junta compresor A/C", parts: "Junta tórica compresor", cost: 50 },
      { description: "Test de estanqueidad", cost: 15 },
    ],
    workPhotos: [],
    mechanicNotes: "Fuga detectada en junta del compresor. Reparada y verificada. Sistema funciona correctamente.",
  },
  {
    id: "a6",
    clientId: "c7",
    vehicleId: "v12",
    mechanicId: "u3",
    date: "2026-03-08T16:00:00",
    serviceType: "neumaticos",
    status: "completada",
    description: "Cambio de los 4 neumáticos a Michelin Pilot Sport 5.",
    estimatedCost: 680,
    finalCost: 680,
    mileageAtService: 35200,
    closedAt: "2026-03-08T18:30:00",
    workItems: [
      { description: "Desmontaje neumáticos antiguos (4 uds)", cost: 40 },
      { description: "Montaje y equilibrado Michelin Pilot Sport 5 225/45 R17", parts: "4x Michelin Pilot Sport 5 225/45 R17", cost: 600 },
      { description: "Alineación de dirección", cost: 40 },
    ],
    workPhotos: [],
    mechanicNotes: "Neumáticos anteriores estaban al 15% de vida. Alineación ajustada. Convergencia correcta.",
  },
  {
    id: "a7",
    clientId: "c4",
    vehicleId: "v7",
    mechanicId: "u3",
    date: "2026-03-20T10:00:00",
    serviceType: "revision_general",
    status: "pendiente",
    description: "Primera revisión de mantenimiento del vehículo eléctrico a los 15.000 km.",
    estimatedCost: 200,
  },
  {
    id: "a8",
    clientId: "c6",
    vehicleId: "v4",
    mechanicId: "u3",
    date: "2026-03-05T09:30:00",
    serviceType: "carroceria",
    status: "cancelada",
    description: "Reparación de arañazo en puerta delantera derecha.",
    estimatedCost: 450,
    notes: "Cliente canceló. Reprogramar para abril.",
  },
];

// ─── Ventas (5) ───────────────────────────────────────────────────────────────

export const sales: Sale[] = [
  {
    id: "s1",
    vehicleId: "v12",
    clientId: "c7",
    sellerId: "u2",
    saleDate: "2026-03-08",
    salePrice: 23700,
    paymentMethod: "contado",
    status: "completada",
    commissionRate: 3,
    commission: 711,
    notes: "Venta directa. El cliente ya conocía el modelo.",
  },
  {
    id: "s2",
    vehicleId: "v3",
    clientId: "c9",
    sellerId: "u2",
    saleDate: "2026-03-10",
    salePrice: 37800,
    paymentMethod: "financiación",
    status: "en_proceso",
    commissionRate: 3,
    commission: 1134,
    financingDetails: "Financiación a 60 meses con Santander Consumer. TAE 6.9%",
    notes: "Financiación pendiente de aprobación bancaria. Señal pagada.",
  },
  {
    id: "s3",
    vehicleId: "v14",
    clientId: "c6",
    sellerId: "u2",
    saleDate: "2026-03-01",
    salePrice: 57500,
    paymentMethod: "leasing",
    status: "completada",
    commissionRate: 3,
    commission: 1725,
    financingDetails: "Leasing empresarial a 48 meses con BBVA. Cuota 890€/mes",
    notes: "Leasing empresarial a 48 meses. Documentación completa.",
  },
  {
    id: "s4",
    vehicleId: "v6",
    clientId: "c2",
    sellerId: "u2",
    saleDate: "2026-02-20",
    salePrice: 22000,
    paymentMethod: "financiación",
    status: "completada",
    commissionRate: 3,
    commission: 660,
    financingDetails: "Financiación a 36 meses con CaixaBank. TAE 5.9%",
  },
  {
    id: "s5",
    vehicleId: "v11",
    clientId: "c4",
    sellerId: "u2",
    saleDate: "2026-03-14",
    salePrice: 26800,
    paymentMethod: "contado",
    status: "en_proceso",
    commissionRate: 3,
    commission: 804,
    notes: "Cliente interesada en el seguro del concesionario.",
  },
];

// ─── Gastos ──────────────────────────────────────────────────────────────────

export const expenses: Expense[] = [
  { id: "e1", category: "compra_vehiculo", description: "Compra BMW Serie 3 320d", amount: 26000, date: "2025-09-01", vehicleId: "v1" },
  { id: "e2", category: "compra_vehiculo", description: "Compra Mercedes-Benz Clase C 220d", amount: 23000, date: "2025-09-05", vehicleId: "v2" },
  { id: "e3", category: "compra_vehiculo", description: "Compra Volkswagen Golf 8 GTI", amount: 31000, date: "2025-10-10", vehicleId: "v3" },
  { id: "e4", category: "reparacion", description: "Reparación carrocería BMW Serie 3", amount: 850, date: "2025-09-15", vehicleId: "v1" },
  { id: "e5", category: "pieza", description: "Neumáticos Michelin Pilot Sport (4 uds)", amount: 680, date: "2025-11-20", vehicleId: "v12" },
  { id: "e6", category: "nomina", description: "Nóminas febrero 2026", amount: 8500, date: "2026-02-28" },
  { id: "e7", category: "nomina", description: "Nóminas marzo 2026", amount: 8500, date: "2026-03-28" },
  { id: "e8", category: "alquiler", description: "Alquiler local marzo 2026", amount: 2200, date: "2026-03-01" },
  { id: "e9", category: "publicidad", description: "Campaña Google Ads marzo", amount: 450, date: "2026-03-05" },
  { id: "e10", category: "seguro", description: "Seguro del local trimestral", amount: 1800, date: "2026-01-15" },
  { id: "e11", category: "impuesto", description: "IVA trimestral Q1 2026", amount: 4200, date: "2026-04-01" },
  { id: "e12", category: "compra_vehiculo", description: "Compra Toyota Corolla Hybrid", amount: 21000, date: "2026-01-05", vehicleId: "v11" },
  { id: "e13", category: "compra_vehiculo", description: "Compra Porsche Macan S", amount: 47000, date: "2026-02-01", vehicleId: "v14" },
  { id: "e14", category: "reparacion", description: "Revisión pre-venta Škoda Octavia", amount: 320, date: "2025-12-20", vehicleId: "v10" },
  { id: "e15", category: "otro", description: "Material de oficina y limpieza", amount: 180, date: "2026-03-10" },
];

// ─── Foro compra-venta ──────────────────────────────────────────────────────

export const forumPosts: ForumPost[] = [
  {
    id: "fp1",
    authorName: "Roberto Gómez",
    authorPhone: "654 321 098",
    authorEmail: "roberto.gomez@gmail.com",
    vehicleBrand: "Hyundai",
    vehicleModel: "Tucson 1.6 CRDi",
    vehicleYear: 2020,
    vehicleMileage: 65000,
    askingPrice: 19500,
    description: "Vendo por cambio a eléctrico. Un solo propietario, siempre en garaje. Revisiones en concesionario oficial.",
    images: [],
    status: "nuevo",
    createdAt: "2026-03-12",
  },
  {
    id: "fp2",
    authorName: "Ana Belén Ruiz",
    authorPhone: "665 432 109",
    vehicleBrand: "Kia",
    vehicleModel: "Sportage 1.6 T-GDi HEV",
    vehicleYear: 2022,
    vehicleMileage: 32000,
    askingPrice: 27000,
    description: "Híbrido con pocos km. Color blanco, llantas 19\". Garantía de fábrica hasta 2029.",
    images: [],
    status: "contactado",
    createdAt: "2026-03-10",
    notes: "Llamada realizada. Queda para ver el coche el viernes.",
  },
  {
    id: "fp3",
    authorName: "David Muñoz",
    authorPhone: "676 543 210",
    authorEmail: "david.munoz@outlook.com",
    vehicleBrand: "Tesla",
    vehicleModel: "Model 3 Long Range",
    vehicleYear: 2023,
    vehicleMileage: 18000,
    askingPrice: 35000,
    description: "Autopilot incluido. Color rojo multicapa. Cargador doméstico incluido en la venta.",
    images: [],
    status: "nuevo",
    createdAt: "2026-03-14",
  },
  {
    id: "fp4",
    authorName: "Marta Iglesias",
    authorPhone: "687 654 321",
    vehicleBrand: "Mazda",
    vehicleModel: "CX-5 2.2 Skyactiv-D",
    vehicleYear: 2019,
    vehicleMileage: 88000,
    askingPrice: 16500,
    description: "Necesito venderlo rápido por traslado al extranjero. Motor en perfecto estado.",
    images: [],
    status: "comprado",
    createdAt: "2026-03-01",
    notes: "Comprado el 08/03. Pendiente de reparación menor.",
  },
];

// ─── Historial de servicio por vehículo ──────────────────────────────────────

export const serviceRecords: VehicleServiceRecord[] = [
  {
    id: "sr1",
    vehicleId: "v10",
    appointmentId: "a4",
    mechanicId: "u3",
    date: "2026-03-12",
    serviceType: "revision_general",
    mileage: 89500,
    workItems: [
      { description: "Revisión de niveles (aceite, refrigerante, frenos)", cost: 0 },
      { description: "Comprobación de frenos y suspensión", cost: 80 },
      { description: "Diagnosis electrónica completa", cost: 60 },
      { description: "Cambio filtro de habitáculo", parts: "Filtro Mann CUK 2939", cost: 35 },
      { description: "Limpieza y ajuste general", cost: 75 },
    ],
    photos: [],
    notes: "Vehículo apto para venta. Neumáticos al 60%.",
  },
  {
    id: "sr2",
    vehicleId: "v2",
    appointmentId: "a5",
    mechanicId: "u3",
    date: "2026-03-10",
    serviceType: "aire_acondicionado",
    mileage: 42300,
    workItems: [
      { description: "Recarga gas R134a", parts: "Gas refrigerante R134a 500g", cost: 45 },
      { description: "Reparación junta compresor A/C", parts: "Junta tórica compresor", cost: 50 },
      { description: "Test de estanqueidad", cost: 15 },
    ],
    photos: [],
    notes: "Fuga reparada y verificada.",
  },
  {
    id: "sr3",
    vehicleId: "v12",
    appointmentId: "a6",
    mechanicId: "u3",
    date: "2026-03-08",
    serviceType: "neumaticos",
    mileage: 35200,
    workItems: [
      { description: "Desmontaje neumáticos antiguos (4 uds)", cost: 40 },
      { description: "Montaje y equilibrado Michelin Pilot Sport 5", parts: "4x Michelin Pilot Sport 5 225/45 R17", cost: 600 },
      { description: "Alineación de dirección", cost: 40 },
    ],
    photos: [],
    notes: "Neumáticos anteriores al 15% de vida.",
  },
];

// ─── Fichas de seguimiento de clientes ──────────────────────────────────────

export const clientVehicleInfo: ClientVehicleInfo[] = [
  { vehicleId: "v2", lastServiceDate: "2026-03-10", lastMileage: 42300, nextOilChangeKm: 50000, nextRevisionDate: "2026-09-10", notes: "A/C reparado en última visita" },
  { vehicleId: "v10", lastServiceDate: "2026-03-12", lastMileage: 89500, nextOilChangeKm: 95000, nextTireChangeKm: 110000, nextRevisionDate: "2027-03-12" },
  { vehicleId: "v12", lastServiceDate: "2026-03-08", lastMileage: 35200, nextOilChangeKm: 45000, nextRevisionDate: "2026-09-08", notes: "Neumáticos nuevos Michelin PS5" },
  { vehicleId: "v1", lastMileage: 28000, nextOilChangeKm: 30000, nextRevisionDate: "2026-06-01", notes: "Cita pendiente para cambio de aceite" },
];

// ─── Helpers ────────────────────────────────────────────────────────────────

export function getServiceRecordsByVehicle(vehicleId: string): VehicleServiceRecord[] {
  return serviceRecords.filter((sr) => sr.vehicleId === vehicleId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getServiceRecordsByMechanic(mechanicId: string): VehicleServiceRecord[] {
  return serviceRecords.filter((sr) => sr.mechanicId === mechanicId).sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

export function getClientVehicleInfo(vehicleId: string): ClientVehicleInfo | undefined {
  return clientVehicleInfo.find((cvi) => cvi.vehicleId === vehicleId);
}

// ─── Helper: obtener entidades por ID ─────────────────────────────────────────

export function getUserById(id: string): User | undefined {
  return users.find((u) => u.id === id);
}

export function getVehicleById(id: string): Vehicle | undefined {
  return vehicles.find((v) => v.id === id);
}

export function getClientById(id: string): Client | undefined {
  return clients.find((c) => c.id === id);
}

// ─── Dashboard stats ──────────────────────────────────────────────────────────

export function getDashboardStats(): DashboardStats {
  const totalVehicles = vehicles.length;
  const availableVehicles = vehicles.filter((v) => v.status === "disponible").length;
  const vehiclesSold = vehicles.filter((v) => v.status === "vendido").length;
  const totalClients = clients.length;
  const pendingAppointments = appointments.filter(
    (a) => a.status === "pendiente" || a.status === "en_progreso"
  ).length;

  const currentMonth = "2026-03";
  const monthlySales = sales.filter(
    (s) => s.saleDate.startsWith(currentMonth) && s.status === "completada"
  );
  const monthlySalesRevenue = monthlySales.reduce((sum, s) => sum + s.salePrice, 0);
  const monthlyCommissions = monthlySales.reduce((sum, s) => sum + s.commission, 0);

  return {
    totalVehicles,
    availableVehicles,
    vehiclesSold,
    totalClients,
    pendingAppointments,
    monthlySalesRevenue,
    monthlyCommissions,
  };
}
